<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="en">
<?php $maindir='/local/Web/sites/php-gcov-web'; require $maindir.'/main.inc'; ?>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  <title>@pagetitle@</title>
  <link rel="stylesheet" type="text/css" href="@basedir@gcov.css">
  <link rel="stylesheet" href="/style.css" />
  <link rel="shortcut icon" href="/favicon.ico" />
</head>
<body bgcolor="#ffffff" text="#000000" link="#000099" alink="#0000ff" vlink="#000099">
<?php include $maindir.'/header.inc'; ?>
<table border="0" cellspacing="0" cellpadding="0"><!-- outer -->
<tr>
<td align="left" valign="top" width="120" bgcolor="#f0f0f0">
<?php include $maindir.'/sidebar.inc'; ?>
</td>
<td bgcolor="#cccccc" background="/images/checkerboard.gif" width="1"><img src="/images/spacer.gif" width="1" height="1" border="0" alt="" /></td>
<td align="left" valign="top">
<table cellpadding="10" cellspacing="0" width="100%"><tr><td align="left" valign="top"><!- content -->
