<?php $heading = isset($mytag) ? $mytag : "PHP: Test and Code Coverage analysis"; ?>
<table border="0" cellspacing="0" cellpadding="0" width="100%" height="67"><!-- header -->
<tr bgcolor="#9999cc"><td rowspan="3" align="center" valign="top" width="126"><a href="http://php.net/"><img src="/images/php.gif" alt="PHP" width="120" height="67" hspace="3" vspace="0"/></a></td><td valign="top"><img src="/images/spacer.gif" width="1" height="17" border="0" alt="" />&nbsp;</td></tr>
<tr bgcolor="#9999cc"><td align='left' class='top' valign='middle'>&nbsp;<?php echo $heading; ?></td></tr>
<tr bgcolor="#9999cc"><td align="right" valign="bottom"><img src="/images/spacer.gif" width="1" height="15" border="0" alt="" /><a href="http://php.net/downloads.php" class="header small">downloads</a> | <a href="http://qa.php.net" class="header small">QA</a> | <a href="http://php.net/docs.php" class="header small">documentation</a> | <a href="http://php.net/FAQ.php" class="header small">faq</a> | <a href="http://php.net/support.php" class="header small">getting help</a> | <a href="http://php.net/mailing-lists.php" class="header small">mailing lists</a> | <a href="http://bugs.php.net/" class="header small">reporting bugs</a> | <a href="http://php.net/sites.php" class="header small">php.net sites</a> | <a href="http://php.net/links.php" class="header small">links</a> | <a href="http://php.net/my.php" class="header small">my php.net</a>&nbsp;</td></tr>
<tr><td colspan="2" bgcolor="#000000" height="1"><img src="gfx/spacer.gif" width="1" height="1" border="0"></td></tr>
<tr><td colspan="2" bgcolor="#7777cc" class="header small">&nbsp;</td></tr>
<tr><td colspan="2" bgcolor="#000000" height="1"><img src="gfx/spacer.gif" width="1" height="1" border="0"></td></tr>
</table><!-- header -->
