#!/usr/local/bin/php -q
<?php

use App\DB;

require_once __DIR__ . '/../../vendor/autoload.php';

$pdo = DB::connect();

$query = "SELECT COUNT(*) AS count,sect FROM note GROUP BY sect ORDER BY count DESC LIMIT 20";
$result = $pdo->safeQuery($query);

$body = "Notes  |  Page\n"
      . "-------+---------------------------------------------------------\n";

$top20 = 0;
foreach ($result as $row) {
  $body .= sprintf("%5d  | https://php.net/manual/en/%s.php\n", $row['count'], $row['sect']);
  $top20 += $row['count'];
}

$query = "SELECT COUNT(*) FROM note";
$total = $pdo->single($query);

$body = "Following are the top 20 pages of the manual, sorted by the number\n"
      . "of user notes contributed. These sections could use a polish, those\n"
      . sprintf("notes represent %.1f%% of the %d total user notes.\n\n", ($top20 / $total)*100, $total)
      . $body;

mail("phpdoc@lists.php.net, php-notes@lists.php.net","Notes Status, $total total",$body,"From: phpdoc@lists.php.net", "-fnoreply@php.net");
