#!/usr/local/bin/php -q
<?php
/*
 This script alerts the php-mirrors team about dead mirrors,
 as well as tries to mail notifications of deactivations
 to the individual mirror maintainers (using the provided
 contact details).
*/

// This script will run for a long time
set_time_limit (0);

// Empty arrays by default
$inactives = $outdated = array();
 
// Try to connect to the database and select phpmasterdb database
mysql_connect("localhost","nobody","") or die("unable to connect to database");
mysql_select_db("phpmasterdb");

// Select last mirror check time from table
$lct = mysql_query("SELECT UNIX_TIMESTAMP(lastchecked) FROM mirrors ORDER BY lastchecked DESC LIMIT 1");
list($checktime) = mysql_fetch_row($lct);

// Select all mirrors ordered by hostname
$query = "SELECT maintainer, hostname, id, UNIX_TIMESTAMP(lastupdated) AS lastupdate, " .
         "phpversion, (DATE_SUB(FROM_UNIXTIME($checktime), INTERVAL 3 DAY) < lastchecked) AS active, " .
         "(DATE_SUB(FROM_UNIXTIME($checktime), INTERVAL 7 DAY) < lastupdated) AS current, ocmt " .
         "FROM mirrors ORDER BY hostname";

// Execute SQL query
$result = mysql_query($query) or die("unable to get from the database");

// Download data to the $hosts array, and count total number of hosts
while ($host = mysql_fetch_assoc($result)) {
    $hosts[] = $host;
}
$total = count($hosts);

// This is the common text for the php-mirrors mail
$body = "Following is data gathered from the various mirrors. It is ordered by those\n"
      . "that are suspected to be dead, mirrors which are alive but have errors, and\n"
      . "finally the rest, sorted by hostname. The maintainers of inactive and outdated\n"
      . "mirror sites are automatically notified the same time, as this mail goes out.\n\n"
      . "Edit mirror listings here: http://master.php.net/manage/mirrors.php\n\n";

// List mirrors which seem to be down
$body .=  "No response was returned from these following hosts within the last three days:\n\n";
for ($i=0; $i < $total; $i++) {
    if (!$hosts[$i]['active']) {
        $body .= sprintf("%s -- %s\n", $hosts[$i]['hostname'], $hosts[$i]['maintainer']);
        $inactives[$hosts[$i]['hostname']] = array($hosts[$i]['maintainer'], $hosts[$i]['ocmt']);
    }
}

// List all mirrors which seem to be outdated
$body .=  "\nThese mirrors have not been updated in at least 7 days:\n\n";
for ($i=0; $i < $total; $i++) {
    if ($hosts[$i]['active'] && !$hosts[$i]['current']) {
        $body .= sprintf("%s -- %s\n", $hosts[$i]['hostname'], $hosts[$i]['maintainer']);
        $outdated[$hosts[$i]['hostname']] = array($hosts[$i]['maintainer'], $hosts[$i]['ocmt']);
    }
}

$body .= "\nAnd now for the rest of the mirrors:\n"
       . "----------------------------------------------------------------------------------------\n"
       . " Host \t\t PHP Version \t\t Last Updated\t\t Maintainer\n"
       . "----------------------------------------------------------------------------------------\n";

/* A note about the padding - given that email readers produce interesting results for spacing,
i've gone for tabs here to help seperate the text columns. to make sure i don't over tab, i do 
a quick strlen check, and depending on how different it is from the string length i give as avg
(first argument), will determine how many tabs i use, or alternatively a space. */

// Padd an item, respecting a default length
function pad($deflen, $item) {
    global $i, $hosts;
    $str = strlen($hosts[$i][$item]);
    if ($str >= $deflen*2) {
        $sp =" ";
    }
    else if ($str <= $deflen){
        $sp ="\t\t";
    } else {
        $sp = "\t";
    }
    return $sp;    
}

for ($i=0; $i < $total; $i++) {
    if ($hosts[$i]['active'] && $hosts[$i]['current']){
        $body .= sprintf(" %s%s%s%s%s\t\t%s\n", $hosts[$i]['hostname'], pad(11, "hostname"), $hosts[$i]['phpversion'], pad(5, "phpversion"), date("F j, Y, g:i a", $hosts[$i]['lastupdate']), $hosts[$i]['maintainer']);
    }
}

$body . "---------------------------------------------------------------------------------------\n";

// Please edit this when testing to send mail to yourself, not to the list every time
mail(
    "php-mirrors@lists.php.net",
    "[mirrors] Status information",
    $body,
    "From: php-mirrors@lists.php.net"
);

// Mail text for those mirror maintainers with inactive mirror sites
$inactives_text = "Hi!\n\nOur automatic mirror site check was unable to reach\n"
                 ."the PHP.net mirror site maintained by you for three or more days\n"
                 ."now, *or* have found a critical error in your mirror setup.\n"
                 ."Therefore our bot automatically disabled your listing as an\n"
                 ."official PHP.net mirror site.\n\n"
                 ."{{lasterror}}"
                 ."Please correct the problem or reply to this mail with your\n"
                 ."questions, if you think that the problem is not on your side.\n\n"
                 ."Mail sent out by the PHP.net automatic mirror site monitoring system";

// Send mail to all inactive mirror maintainers
foreach ($inactives as $hostname => $hostinfo) {
    if (!empty($hostinfo[1])) {
        $last_error = "The last error message stored for your mirror is:\n  {$hostinfo[1]}\n\n";
    }
    else { $last_error = ""; }
    mail(
        $hostinfo[0],
        "$hostname mirror site deactivated",
        str_replace("{{lasterror}}", $last_error, $inactives_text),
        "From: php-mirrors@lists.php.net\r\nBcc: goba@php.net"
    );
}

// Mail text for those mirror maintainers with outdated mirror sites
$outdated_text = "Hi!\n\nOur automatic mirror site check found out, that\n"
                 ."the PHP.net mirror site maintained by you was not updated in\n"
                 ."the last seven or more days, and therefore automatically disabled\n"
                 ."your listing as a PHP.net mirror site.\n\n"
                 ."Please correct the problem or reply to this mail with your\n"
                 ."questions, if you think that the problem is not on your side.\n\n"
                 ."Mail sent out by the PHP.net automatic mirror site monitoring system";

// Send mail to all outdated mirror maintainers
foreach ($outdated as $hostname => $hostinfo) {
    mail(
        $hostinfo[0],
        "$hostname mirror site deactivated",
        $outdated_text,
        "From: php-mirrors@lists.php.net"
    );
}
