#!/usr/local/bin/php -q
<?php /* vim: set noet ts=2 sw=2 ft=php3: : */

$token = getenv("TOKEN");
if (!$token) die("you have to set the TOKEN environment variable");
$token = rawurlencode($token);

if (!$argv[1]) die("usage: $argv[0] directory\n");

$root = $argv[1];

/* get mirrors list */
fetch_into_file("http://master.php.net/fetch/mirrors.php?token=$token",
                "$root/include/mirrors.inc");

/* get upcoming events */
fetch_into_file("http://master.php.net/fetch/events.php?nm=3&token=$token",
                "$root/backend/events.csv");

function fetch_into_file($url,$file) {
  $source = @fopen($url,"r");
  if (!$source) {
    return;
  }

  $dest = @fopen("$file~","w");
  if (!$dest) {
    echo "failed to open '$file~' for writing\n";
    return;
  }

  while (!feof($source)) {
    $chunk = fread($source,4096);
    if (fwrite($dest,$chunk) < 0) {
      fclose($source); fclose($dest);
      unlink("$file~");
      echo "failed writing to '$file~'\n";
      return;
    }
  }
  fclose($source); fclose($dest);

  if (!@filesize("$file~")) {
    echo "'$file~' was empty, skipping\n";
    unlink("$file~");
    return;
  }
  
  return rename("$file~",$file);
}
